name: React CI - build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      
      - name: Build app
        run: npm run build
      
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/prod'
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/{{ secrets.VERCEL_PROD_HOOK }}
